apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "awg-appdev-init.fullname" . }}-conf
  labels:
    {{- include "awg-appdev-init.labels" . | nindent 4 }}
  annotations:
    crossplane.io/external-name: awg-appdev-conf
spec:
  reclaimPolicy: Delete
  providerConfigRef:
    name: default
  forProvider:
    namespace: {{ .Release.Namespace }}
    chart:
      repository: oci://{{ .Values.repoHost }}/charts
      name: awg-appdev-conf
      version: {{ .Chart.Version | quote }}
    values:
      repoHost: {{ .Values.repoHost | quote }}
      security:
{{ .Values.security | toYaml | indent 8 }}
    wait: true
