apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "awg-appdev-init.fullname" . }}-kyverno
  labels:
    {{- include "awg-appdev-init.labels" . | nindent 4 }}
  annotations:
    crossplane.io/external-name: kyverno
spec:
  reclaimPolicy: Delete
  providerConfigRef:
    name: default
  forProvider:
    namespace: kyverno
    chart:
      repository: https://kyverno.github.io/kyverno/
      name: kyverno
      version: 3.3.7
    values:
      features:
        logging:
          verbosity: 4
      admissionController:
        replicas: 3
        rbac:
          clusterRole:
            extraResources:
            - apiGroups:
              - ""
              resources:
              - pods
              - serviceaccounts
              verbs:
              - get
              - list
              - watch
              - update
            - apiGroups:
              - apps
              resources:
              - deployments
              verbs:
              - get
              - list
              - watch
              - update
            - apiGroups:
              - appdev.awginc.com
              resources:
              - "*"
              verbs:
              - get
              - list
              - watch
      backgroundController:
        replicas: 2
        rbac:
          clusterRole:
            extraResources:
            - apiGroups:
              - ""
              resources:
              - pods
              - serviceaccounts
              verbs:
              - get
              - list
              - watch
              - update
            - apiGroups:
              - apps
              resources:
              - deployments
              verbs:
              - get
              - list
              - watch
              - update
            - apiGroups:
              - appdev.awginc.com
              resources:
              - "*"
              verbs:
              - get
              - list
              - watch
      cleanupController:
        replicas: 1
        rbac:
          clusterRole:
            extraResources:
            - apiGroups:
              - appdev.awginc.com
              resources:
              - "*"
              verbs:
              - get
              - list
              - watch
      reportsController:
        replicas: 2
        rbac:
          clusterRole:
            extraResources:
            - apiGroups:
              - appdev.awginc.com
              resources:
              - "*"
              verbs:
              - get
              - list
              - watch
