apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "awg-appdev-init.fullname" . }}-traefik-external
  labels:
    {{- include "awg-appdev-init.labels" . | nindent 4 }}
  annotations:
    crossplane.io/external-name: traefik-external
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  rollbackLimit: 1000
  forProvider:
    namespace: traefik
    chart:
      repository: https://traefik.github.io/charts
      name: traefik
      version: 35.0.1
    wait: true
    values:
      ports:
        web:
          port: 80
        websecure:
          port: 443
      providers:
        kubernetesIngress:
          ingressClass: traefik-external
          publishedService:
            enabled: true
        kubernetesGateway:
          enabled: true
          labelSelector: "traefik-instance=traefik-internal"
      ingressClass:
        enabled: true
        isDefaultClass: false
        name: traefik-external
      gatewayClass:
        enabled: true
        name: traefik-external
        labels:
          traefik-instance: traefik-external
      gateway:
        enabled: false
      service:
        type: LoadBalancer
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 75
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 75
      logs:
        access:
          bufferingSize: 128
          enabled: true
