apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{ include "awg-appdev-init.fullname" . }}-trust-manager
  labels:
    {{- include "awg-appdev-init.labels" . | nindent 4 }}
  annotations:
    crossplane.io/external-name: trust-manager
spec:
  providerConfigRef:
    name: default
  deletionPolicy: Delete
  rollbackLimit: 1000
  forProvider:
    namespace: cert-manager
    chart:
      repository: https://charts.jetstack.io
      name: trust-manager
      version: v0.16.0
    wait: true
    values:
      secretTargets:
        enabled: true
        authorizedSecretsAll: true
