apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: awg-appdev
  labels:
    {{- include "awg-appdev-init.labels" . | nindent 4 }}
spec:
  ignoreCrossplaneConstraints: false
  package: {{ .Values.repoHost }}/xpkgs/awg-appdev:{{ .Chart.AppVersion  }}
