apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: namespaces.servicebus.azure.appdev.awginc.com
  labels:
    crossplane.io/xrd: xnamespaces.servicebus.azure.appdev.awginc.com
spec:
  compositeTypeRef:
    apiVersion: servicebus.azure.appdev.awginc.com/v1alpha1
    kind: XNamespace
  writeConnectionSecretsToNamespace: crossplane-system
  mode: Pipeline
  pipeline:
  - step: env
    functionRef:
      name: crossplane-contrib-function-environment-configs
    input:
      apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
      kind: Input
      spec:
        environmentConfigs:
          - type: Reference
            ref:
              name: awg-appdev
  - step: render
    functionRef:
      name: crossplane-contrib-function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          ---
          {{- $environment := .context | dig "apiextensions.crossplane.io/environment" "" }}
          {{- if not $environment }}
          {{- fail "Could not load environment config." }}
          {{- end }}
          {{- $defaultName := $environment.defaultName | trim }}
          ---

          {{- $xr := getCompositeResource . }}
          {{- $namespace := $xr.spec.claimRef.namespace }}
          {{- $name := $xr.spec.claimRef.name }}
          {{- $appRef := $xr.spec.applicationRef.name }}
          {{- $hash := printf "%s-%s" $namespace $name | sha1sum | substr 0 5 }}
          ---

          apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
          kind: ExtraResources
          requirements:
            application:
              apiVersion: appdev.awginc.com/v1alpha1
              kind: XApplication
              matchLabels:
                crossplane.io/claim-namespace: {{ $namespace }}
                crossplane.io/claim-name: {{ $appRef }}
          ---

          {{- if .extraResources }}
          {{- $appXR := .extraResources | dig "application" "items" list | first | default dict | dig "resource" dict }}
          {{- if not $appXR }}
          {{- fail (printf "Could not find Application: %s/%s" $namespace $appRef) }}
          {{- end }}
          ---

          {{- $resourceName := printf "%s-app-%s-%s" $defaultName $appXR.spec.name $hash }}
          ---

          {{- $serviceBusNamespaceName := $resourceName}}
          {{- if gt (len $serviceBusNamespaceName) 50 }}
          {{- $serviceBusNamespaceName = printf "%s-%s" (substr 0 ((sub 50 6) | int) $serviceBusNamespaceName | trimSuffix "-") (sha1sum $serviceBusNamespaceName | substr 0 5) }}
          {{- end }}
          apiVersion: servicebus.azure.upbound.io/v1beta2
          kind: ServiceBusNamespace
          metadata:
            annotations:
              {{ setResourceNameAnnotation "namespace" }}
              crossplane.io/external-name: {{ $serviceBusNamespaceName }}
            labels:
              application.appdev.awginc.com/namespace: {{ $namespace }}
              application.appdev.awginc.com/name: {{ $appRef }}
          spec:
            managementPolicies:
            - Observe
            - Create
            - Update
            - Delete
            forProvider:
              tags:
                application.appdev.awginc.com-namespace: {{ $namespace }}
                application.appdev.awginc.com-name: {{ $appRef }}
                namespace.servicebus.azure.appdev.awginc.com-name: {{ $xr.metadata.name }}
              resourceGroupNameSelector:
                matchLabels:
                  application.appdev.awginc.com/namespace: {{ $namespace }}
                  application.appdev.awginc.com/name: {{ $appRef }}
              location: {{ $xr.spec.location | default $appXR.spec.defaultResourceLocation }}
              sku: Standard
            writeConnectionSecretToRef:
              namespace: crossplane-system
              name: {{ $xr.metadata.uid }}-namespace
          ---

          apiVersion: servicebus.azure.appdev.awginc.com/v1alpha1
          kind: XNamespace
          status:
            applicationRef:
              namespace: {{ $namespace }}
              name: {{ $appRef }}
          ---

          {{- $serviceBus := getComposedResource . "namespace" }}
          {{- if dig "status" "atProvider" "id" "" $serviceBus }}
          ---

          apiVersion: servicebus.azure.appdev.awginc.com/v1alpha1
          kind: XNamespace
          status:
            azure:
              resources:
                serviceBusNamespace:
                  {{- with $serviceBus.status.atProvider.id }}
                  id: {{ . }}
                  {{- end }}
                  {{- with $serviceBus.metadata.annotations | dig "crossplane.io/external-name" "" }}
                  name: {{ . }}
                  {{- end }}
                  {{- with $serviceBus.status.atProvider.location }}
                  location: {{ . }}
                  {{- end }}
                  {{- with $serviceBus.status.atProvider.managedBy }}
                  managedBy: {{ . }}
                  {{- end }}
          ---

          apiVersion: authorization.azure.upbound.io/v1beta1
          kind: RoleAssignment
          metadata:
            annotations:
              {{ setResourceNameAnnotation "role-owner" }}
            labels:
              application.appdev.awginc.com/namespace: {{ $namespace }}
              application.appdev.awginc.com/name: {{ $name }}
          spec:
            managementPolicies:
            - Observe
            - Create
            - Update
            - Delete
            forProvider:
              roleDefinitionName: Azure Service Bus Data Owner
              scope: {{ $serviceBus.status.atProvider.id }}
              principalId: {{ $appXR.status.azure.resources.userAssignedIdentity.principalId }}
          ---

          apiVersion: authorization.azure.upbound.io/v1beta1
          kind: RoleAssignment
          metadata:
            annotations:
              {{ setResourceNameAnnotation "role-sender" }}
            labels:
              application.appdev.awginc.com/namespace: {{ $namespace }}
              application.appdev.awginc.com/name: {{ $name }}
          spec:
            managementPolicies:
            - Observe
            - Create
            - Update
            - Delete
            forProvider:
              roleDefinitionName: Azure Service Bus Data Sender
              scope: {{ $serviceBus.status.atProvider.id }}
              principalId: {{ $appXR.status.azure.resources.userAssignedIdentity.principalId }}
          ---

          apiVersion: authorization.azure.upbound.io/v1beta1
          kind: RoleAssignment
          metadata:
            annotations:
              {{ setResourceNameAnnotation "role-receiver" }}
            labels:
              application.appdev.awginc.com/namespace: {{ $namespace }}
              application.appdev.awginc.com/name: {{ $name }}
          spec:
            managementPolicies:
            - Observe
            - Create
            - Update
            - Delete
            forProvider:
              roleDefinitionName: Azure Service Bus Data Receiver
              scope: {{ $serviceBus.status.atProvider.id }}
              principalId: {{ $appXR.status.azure.resources.userAssignedIdentity.principalId }}
          ---

          apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
          kind: CompositeConnectionDetails
          data:
            {{- $namespaceConnectionDetails := .observed.resources.namespace.connectionDetails }}
            {{- if $namespaceConnectionDetails }}
            endpoint: {{ $serviceBus.status.atProvider.endpoint | b64enc }}
            defaultPrimaryConnectionString: {{ index $namespaceConnectionDetails "attribute.default_primary_connection_string" }}
            defaultPrimaryKey: {{ index $namespaceConnectionDetails "attribute.default_primary_key" }}
            defaultSecondaryConnectionString: {{ index $namespaceConnectionDetails "attribute.default_secondary_connection_string" }}
            defaultSecondaryKey: {{ index $namespaceConnectionDetails "attribute.default_secondary_key" }}
            {{- end }}
          ---

          {{- end }}
          {{- end }}
          ---
  - step: ready
    functionRef:
      name: crossplane-contrib-function-auto-ready
