apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: external
  labels:
    {{- include "awg-appdev-conf.labels" . | nindent 4 }}
spec:
  acme:
    server: {{ .Values.security.issuers.external.server }}
    email: {{ .Values.security.issuers.external.email }}
    privateKeySecretRef:
      name: external-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik-external
