apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xapplications.appdev.awginc.com
spec:
  group: appdev.awginc.com
  names:
    kind: XApplication
    plural: xapplications
  claimNames:
    kind: Application
    plural: applications
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              metadataLocation:
                type: string
              defaultResourceLocation:
                type: string
            required:
            - name
            - metadataLocation
            - defaultResourceLocation
