apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-04-17T18:39:56Z"
  generation: 1
  name: accounts.storage.azure.appdev.awginc.com
  ownerReferences:
  - apiVersion: apiextensions.crossplane.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: CompositeResourceDefinition
    name: xaccounts.storage.azure.appdev.awginc.com
    uid: 4d7d433b-56c2-4956-86d7-555f6ffb6408
  resourceVersion: "4579097"
  uid: 758ea4db-ad68-4b34-a4c0-1c9373de5801
spec:
  conversion:
    strategy: None
  group: storage.azure.appdev.awginc.com
  names:
    categories:
    - claim
    kind: Account
    listKind: AccountList
    plural: accounts
    singular: account
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Synced')].status
      name: SYNCED
      type: string
    - jsonPath: .status.conditions[?(@.type=='Ready')].status
      name: READY
      type: string
    - jsonPath: .spec.writeConnectionSecretToRef.name
      name: CONNECTION-SECRET
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            properties:
              name:
                maxLength: 63
                type: string
            type: object
          spec:
            properties:
              applicationRef:
                properties:
                  name:
                    type: string
                type: object
              compositeDeletePolicy:
                default: Background
                enum:
                - Background
                - Foreground
                type: string
              compositionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionRevisionRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              compositionRevisionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              compositionSelector:
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - matchLabels
                type: object
              compositionUpdatePolicy:
                enum:
                - Automatic
                - Manual
                type: string
              location:
                type: string
              publishConnectionDetailsTo:
                properties:
                  configRef:
                    default:
                      name: default
                    properties:
                      name:
                        type: string
                    type: object
                  metadata:
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                      type:
                        type: string
                    type: object
                  name:
                    type: string
                required:
                - name
                type: object
              resourceRef:
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - apiVersion
                - kind
                - name
                type: object
              writeConnectionSecretToRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            type: object
          status:
            properties:
              applicationRef:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                type: object
              azure:
                properties:
                  resources:
                    properties:
                      storageAccount:
                        properties:
                          id:
                            type: string
                          location:
                            type: string
                          managedBy:
                            type: string
                          name:
                            type: string
                        type: object
                    type: object
                type: object
              claimConditionTypes:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
              conditions:
                description: Conditions of the resource.
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              connectionDetails:
                properties:
                  lastPublishedTime:
                    format: date-time
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - claim
    kind: Account
    listKind: AccountList
    plural: accounts
    singular: account
  conditions:
  - lastTransitionTime: "2025-04-17T18:39:56Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-04-17T18:39:56Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
