apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xaccounts.storage.azure.appdev.awginc.com
spec:
  group: storage.azure.appdev.awginc.com
  names:
    kind: XAccount
    plural: xaccounts
  claimNames:
    kind: Account
    plural: accounts
  connectionSecretKeys:
  - accountName
  - primaryAccessKey
  - secondaryAccessKey
  - primaryConnectionString
  - secondaryConnectionString
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              applicationRef:
                type: object
                properties:
                  name:
                    type: string
              location:
                type: string
          status:
            properties:
              applicationRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              azure:
                type: object
                properties:
                  resources:
                    type: object
                    properties:
                      storageAccount:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          location:
                            type: string
                          managedBy:
                            type: string
