jobs:
- deployment: deploy
  displayName: Deploy
  pool:
    vmImage: 'ubuntu-24.04'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: artifacts
      
        - task: gitversion/setup@0
          inputs:
            versionSpec: 5.x
          
        - task: gitversion/execute@0
          inputs:
            versionSpec: 5.x

        - bash: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          displayName: Install Taskfile
        - bash: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          displayName: Upgrade Azure CLI
        - task: HelmInstaller@1
          displayName: Install helm
        - task: GoTool@0
          displayName: Install Go
          inputs:
            version: '1.10'
        - task: Go@0
          displayName: Install Crane
          inputs:
            command: 'get'
            arguments: 'github.com/google/go-containerregistry/cmd/gcrane@latest'

        - bash: task publish VERSION=$(GitVersion.SemVer) CONTAINERREGISTRY=$(ContainerRegistry)
          displayName: Publish Artifacts
          workingDirectory: $(Pipeline.Workspace)/artifacts
